# CUB-200-2011 Bird Dataset Configuration - CORRECTED
path: data
train: train/images
val: val/images
test: test/images

# Number of classes - FIXED TO 200
nc: 200

# Class names (all 200 CUB classes)
names:
  0: '001.Black footed Albatross'
  1: '002.Laysan Albatross'
  2: '003.Sooty Albatross'
  3: '004.Groove billed Ani'
  4: '005.Crested Auklet'
  5: '006.Least Auklet'
  6: '007.Parakeet Auklet'
  7: '008.Rhinoceros Auklet'
  8: '009.Brewer Blackbird'
  9: '010.Red winged Blackbird'
  10: '011.Rusty Blackbird'
  11: '012.Yellow headed Blackbird'
  12: '013.Bobolink'
  13: '014.Indigo Bunting'
  14: '015.Lazuli Bunting'
  15: '016.Painted Bunting'
  16: '017.Cardinal'
  17: '018.Spotted Catbird'
  18: '019.Gray Catbird'
  19: '020.Yellow breasted Chat'
  20: '021.Eastern Towhee'
  21: '022.Chuck will Widow'
  22: '023.Brandt Cormorant'
  23: '024.Red faced Cormorant'
  24: '025.Pelagic Cormorant'
  25: '026.Bronzed Cowbird'
  26: '027.Shiny Cowbird'
  27: '028.Brown Creeper'
  28: '029.American Crow'
  29: '030.Fish Crow'
  30: '031.Black billed Cuckoo'
  31: '032.Mangrove Cuckoo'
  32: '033.Yellow billed Cuckoo'
  33: '034.Gray crowned Rosy Finch'
  34: '035.Purple Finch'
  35: '036.Northern Flicker'
  36: '037.Acadian Flycatcher'
  37: '038.Great Crested Flycatcher'
  38: '039.Least Flycatcher'
  39: '040.Olive sided Flycatcher'
  40: '041.Scissor tailed Flycatcher'
  41: '042.Vermilion Flycatcher'
  42: '043.Yellow bellied Flycatcher'
  43: '044.Frigatebird'
  44: '045.Northern Fulmar'
  45: '046.Gadwall'
  46: '047.American Goldfinch'
  47: '048.European Goldfinch'
  48: '049.Boat tailed Grackle'
  49: '050.Eared Grebe'
  50: '051.Horned Grebe'
  51: '052.Pied billed Grebe'
  52: '053.Western Grebe'
  53: '054.Blue Grosbeak'
  54: '055.Evening Grosbeak'
  55: '056.Pine Grosbeak'
  56: '057.Rose breasted Grosbeak'
  57: '058.Pigeon Guillemot'
  58: '059.California Gull'
  59: '060.Glaucous winged Gull'
  60: '061.Heermann Gull'
  61: '062.Herring Gull'
  62: '063.Ivory Gull'
  63: '064.Ring billed Gull'
  64: '065.Slaty backed Gull'
  65: '066.Western Gull'
  66: '067.Anna Hummingbird'
  67: '068.Ruby throated Hummingbird'
  68: '069.Rufous Hummingbird'
  69: '070.Green Violetear'
  70: '071.Long tailed Jaeger'
  71: '072.Pomarine Jaeger'
  72: '073.Blue Jay'
  73: '074.Florida Jay'
  74: '075.Green Jay'
  75: '076.Dark eyed Junco'
  76: '077.Tropical Kingbird'
  77: '078.Gray Kingbird'
  78: '079.Belted Kingfisher'
  79: '080.Green Kingfisher'
  80: '081.Pied Kingfisher'
  81: '082.Ringed Kingfisher'
  82: '083.White breasted Kingfisher'
  83: '084.Red legged Kittiwake'
  84: '085.Horned Lark'
  85: '086.Pacific Loon'
  86: '087.Mallard'
  87: '088.Western Meadowlark'
  88: '089.Hooded Merganser'
  89: '090.Red breasted Merganser'
  90: '091.Mockingbird'
  91: '092.Nighthawk'
  92: '093.Clark Nutcracker'
  93: '094.White breasted Nuthatch'
  94: '095.Baltimore Oriole'
  95: '096.Hooded Oriole'
  96: '097.Orchard Oriole'
  97: '098.Scott Oriole'
  98: '099.Ovenbird'
  99: '100.Brown Pelican'
  100: '101.White Pelican'
  101: '102.Western Wood Pewee'
  102: '103.Sayornis'
  103: '104.American Pipit'
  104: '105.Whip poor Will'
  105: '106.Horned Puffin'
  106: '107.Common Raven'
  107: '108.White necked Raven'
  108: '109.American Redstart'
  109: '110.Geococcyx'
  110: '111.Loggerhead Shrike'
  111: '112.Great Grey Shrike'
  112: '113.Baird Sparrow'
  113: '114.Black throated Sparrow'
  114: '115.Brewer Sparrow'
  115: '116.Chipping Sparrow'
  116: '117.Clay colored Sparrow'
  117: '118.House Sparrow'
  118: '119.Field Sparrow'
  119: '120.Fox Sparrow'
  120: '121.Grasshopper Sparrow'
  121: '122.Harris Sparrow'
  122: '123.Henslow Sparrow'
  123: '124.Le Conte Sparrow'
  124: '125.Lincoln Sparrow'
  125: '126.Nelson Sharp tailed Sparrow'
  126: '127.Savannah Sparrow'
  127: '128.Seaside Sparrow'
  128: '129.Song Sparrow'
  129: '130.Tree Sparrow'
  130: '131.Vesper Sparrow'
  131: '132.White crowned Sparrow'
  132: '133.White throated Sparrow'
  133: '134.Cape Glossy Starling'
  134: '135.Bank Swallow'
  135: '136.Barn Swallow'
  136: '137.Cliff Swallow'
  137: '138.Tree Swallow'
  138: '139.Scarlet Tanager'
  139: '140.Summer Tanager'
  140: '141.Artic Tern'
  141: '142.Black Tern'
  142: '143.Caspian Tern'
  143: '144.Common Tern'
  144: '145.Elegant Tern'
  145: '146.Forsters Tern'
  146: '147.Least Tern'
  147: '148.Green tailed Towhee'
  148: '149.Brown Thrasher'
  149: '150.Sage Thrasher'
  150: '151.Black capped Vireo'
  151: '152.Blue headed Vireo'
  152: '153.Philadelphia Vireo'
  153: '154.Red eyed Vireo'
  154: '155.Warbling Vireo'
  155: '156.White eyed Vireo'
  156: '157.Yellow throated Vireo'
  157: '158.Bay breasted Warbler'
  158: '159.Black and white Warbler'
  159: '160.Black throated Blue Warbler'
  160: '161.Blue winged Warbler'
  161: '162.Canada Warbler'
  162: '163.Cape May Warbler'
  163: '164.Cerulean Warbler'
  164: '165.Chestnut sided Warbler'
  165: '166.Golden winged Warbler'
  166: '167.Hooded Warbler'
  167: '168.Kentucky Warbler'
  168: '169.Magnolia Warbler'
  169: '170.Mourning Warbler'
  170: '171.Myrtle Warbler'
  171: '172.Nashville Warbler'
  172: '173.Orange crowned Warbler'
  173: '174.Palm Warbler'
  174: '175.Pine Warbler'
  175: '176.Prairie Warbler'
  176: '177.Prothonotary Warbler'
  177: '178.Swainson Warbler'
  178: '179.Tennessee Warbler'
  179: '180.Wilson Warbler'
  180: '181.Worm eating Warbler'
  181: '182.Yellow Warbler'
  182: '183.Northern Waterthrush'
  183: '184.Louisiana Waterthrush'
  184: '185.Bohemian Waxwing'
  185: '186.Cedar Waxwing'
  186: '187.American Three toed Woodpecker'
  187: '188.Pileated Woodpecker'
  188: '189.Red bellied Woodpecker'
  189: '190.Red cockaded Woodpecker'
  190: '191.Red headed Woodpecker'
  191: '192.Downy Woodpecker'
  192: '193.Bewick Wren'
  193: '194.Cactus Wren'
  194: '195.Carolina Wren'
  195: '196.House Wren'
  196: '197.Marsh Wren'
  197: '198.Rock Wren'
  198: '199.Winter Wren'
  199: '200.Common Yellowthroat'